/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BootRouteImport } from './routes/boot'
import { Route as CordisRouteImport } from './routes/cordis'
import { Route as EnRouteImport } from './routes/en'
import { Route as EventsRouteImport } from './routes/events'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as GlossaryRouteImport } from './routes/glossary'
import { Route as LoopRouteImport } from './routes/loop'
import { Route as MapRouteImport } from './routes/map'
import { Route as ModulesRouteImport } from './routes/modules'
import { Route as PrinciplesRouteImport } from './routes/principles'
import { Route as SeamsRouteImport } from './routes/seams'
import { Route as StoryRouteImport } from './routes/story'
import { Route as ApiLocaleSuggestionRouteImport } from './routes/api.locale-suggestion'
import { Route as EnIndexRouteImport } from './routes/en.index'
import { Route as EnBootRouteImport } from './routes/en.boot'
import { Route as EnCordisRouteImport } from './routes/en.cordis'
import { Route as EnEventsRouteImport } from './routes/en.events'
import { Route as EnFaqRouteImport } from './routes/en.faq'
import { Route as EnGlossaryRouteImport } from './routes/en.glossary'
import { Route as EnLoopRouteImport } from './routes/en.loop'
import { Route as EnMapRouteImport } from './routes/en.map'
import { Route as EnModulesRouteImport } from './routes/en.modules'
import { Route as EnPrinciplesRouteImport } from './routes/en.principles'
import { Route as EnSeamsRouteImport } from './routes/en.seams'
import { Route as EnStoryRouteImport } from './routes/en.story'
import { Route as ModulesIndexRouteImport } from './routes/modules.index'
import { Route as ModulesSlugRouteImport } from './routes/modules.$slug'
import { Route as EnModulesIndexRouteImport } from './routes/en.modules.index'
import { Route as EnModulesSlugRouteImport } from './routes/en.modules.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BootRoute = BootRouteImport.update({
  id: '/boot',
  path: '/boot',
  getParentRoute: () => rootRouteImport,
} as any)
const CordisRoute = CordisRouteImport.update({
  id: '/cordis',
  path: '/cordis',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRoute = EnRouteImport.update({
  id: '/en',
  path: '/en',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryRoute = GlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const LoopRoute = LoopRouteImport.update({
  id: '/loop',
  path: '/loop',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesRoute = ModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => rootRouteImport,
} as any)
const PrinciplesRoute = PrinciplesRouteImport.update({
  id: '/principles',
  path: '/principles',
  getParentRoute: () => rootRouteImport,
} as any)
const SeamsRoute = SeamsRouteImport.update({
  id: '/seams',
  path: '/seams',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLocaleSuggestionRoute = ApiLocaleSuggestionRouteImport.update({
  id: '/api/locale-suggestion',
  path: '/api/locale-suggestion',
  getParentRoute: () => rootRouteImport,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnRoute,
} as any)
const EnBootRoute = EnBootRouteImport.update({
  id: '/boot',
  path: '/boot',
  getParentRoute: () => EnRoute,
} as any)
const EnCordisRoute = EnCordisRouteImport.update({
  id: '/cordis',
  path: '/cordis',
  getParentRoute: () => EnRoute,
} as any)
const EnEventsRoute = EnEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => EnRoute,
} as any)
const EnFaqRoute = EnFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => EnRoute,
} as any)
const EnGlossaryRoute = EnGlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => EnRoute,
} as any)
const EnLoopRoute = EnLoopRouteImport.update({
  id: '/loop',
  path: '/loop',
  getParentRoute: () => EnRoute,
} as any)
const EnMapRoute = EnMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => EnRoute,
} as any)
const EnModulesRoute = EnModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => EnRoute,
} as any)
const EnPrinciplesRoute = EnPrinciplesRouteImport.update({
  id: '/principles',
  path: '/principles',
  getParentRoute: () => EnRoute,
} as any)
const EnSeamsRoute = EnSeamsRouteImport.update({
  id: '/seams',
  path: '/seams',
  getParentRoute: () => EnRoute,
} as any)
const EnStoryRoute = EnStoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => EnRoute,
} as any)
const ModulesIndexRoute = ModulesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ModulesRoute,
} as any)
const ModulesSlugRoute = ModulesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ModulesRoute,
} as any)
const EnModulesIndexRoute = EnModulesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnModulesRoute,
} as any)
const EnModulesSlugRoute = EnModulesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EnModulesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/boot': typeof BootRoute
  '/cordis': typeof CordisRoute
  '/en': typeof EnRouteWithChildren
  '/events': typeof EventsRoute
  '/faq': typeof FaqRoute
  '/glossary': typeof GlossaryRoute
  '/loop': typeof LoopRoute
  '/map': typeof MapRoute
  '/modules': typeof ModulesRouteWithChildren
  '/principles': typeof PrinciplesRoute
  '/seams': typeof SeamsRoute
  '/story': typeof StoryRoute
  '/api/locale-suggestion': typeof ApiLocaleSuggestionRoute
  '/en/boot': typeof EnBootRoute
  '/en/cordis': typeof EnCordisRoute
  '/en/events': typeof EnEventsRoute
  '/en/faq': typeof EnFaqRoute
  '/en/glossary': typeof EnGlossaryRoute
  '/en/loop': typeof EnLoopRoute
  '/en/map': typeof EnMapRoute
  '/en/modules': typeof EnModulesRouteWithChildren
  '/en/principles': typeof EnPrinciplesRoute
  '/en/seams': typeof EnSeamsRoute
  '/en/story': typeof EnStoryRoute
  '/modules/$slug': typeof ModulesSlugRoute
  '/en/': typeof EnIndexRoute
  '/modules/': typeof ModulesIndexRoute
  '/en/modules/$slug': typeof EnModulesSlugRoute
  '/en/modules/': typeof EnModulesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/boot': typeof BootRoute
  '/cordis': typeof CordisRoute
  '/events': typeof EventsRoute
  '/faq': typeof FaqRoute
  '/glossary': typeof GlossaryRoute
  '/loop': typeof LoopRoute
  '/map': typeof MapRoute
  '/principles': typeof PrinciplesRoute
  '/seams': typeof SeamsRoute
  '/story': typeof StoryRoute
  '/api/locale-suggestion': typeof ApiLocaleSuggestionRoute
  '/en/boot': typeof EnBootRoute
  '/en/cordis': typeof EnCordisRoute
  '/en/events': typeof EnEventsRoute
  '/en/faq': typeof EnFaqRoute
  '/en/glossary': typeof EnGlossaryRoute
  '/en/loop': typeof EnLoopRoute
  '/en/map': typeof EnMapRoute
  '/en/principles': typeof EnPrinciplesRoute
  '/en/seams': typeof EnSeamsRoute
  '/en/story': typeof EnStoryRoute
  '/modules/$slug': typeof ModulesSlugRoute
  '/en': typeof EnIndexRoute
  '/modules': typeof ModulesIndexRoute
  '/en/modules/$slug': typeof EnModulesSlugRoute
  '/en/modules': typeof EnModulesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/boot': typeof BootRoute
  '/cordis': typeof CordisRoute
  '/en': typeof EnRouteWithChildren
  '/events': typeof EventsRoute
  '/faq': typeof FaqRoute
  '/glossary': typeof GlossaryRoute
  '/loop': typeof LoopRoute
  '/map': typeof MapRoute
  '/modules': typeof ModulesRouteWithChildren
  '/principles': typeof PrinciplesRoute
  '/seams': typeof SeamsRoute
  '/story': typeof StoryRoute
  '/api/locale-suggestion': typeof ApiLocaleSuggestionRoute
  '/en/boot': typeof EnBootRoute
  '/en/cordis': typeof EnCordisRoute
  '/en/events': typeof EnEventsRoute
  '/en/faq': typeof EnFaqRoute
  '/en/glossary': typeof EnGlossaryRoute
  '/en/loop': typeof EnLoopRoute
  '/en/map': typeof EnMapRoute
  '/en/modules': typeof EnModulesRouteWithChildren
  '/en/principles': typeof EnPrinciplesRoute
  '/en/seams': typeof EnSeamsRoute
  '/en/story': typeof EnStoryRoute
  '/modules/$slug': typeof ModulesSlugRoute
  '/en/': typeof EnIndexRoute
  '/modules/': typeof ModulesIndexRoute
  '/en/modules/$slug': typeof EnModulesSlugRoute
  '/en/modules/': typeof EnModulesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/boot'
    | '/cordis'
    | '/en'
    | '/events'
    | '/faq'
    | '/glossary'
    | '/loop'
    | '/map'
    | '/modules'
    | '/principles'
    | '/seams'
    | '/story'
    | '/api/locale-suggestion'
    | '/en/boot'
    | '/en/cordis'
    | '/en/events'
    | '/en/faq'
    | '/en/glossary'
    | '/en/loop'
    | '/en/map'
    | '/en/modules'
    | '/en/principles'
    | '/en/seams'
    | '/en/story'
    | '/modules/$slug'
    | '/en/'
    | '/modules/'
    | '/en/modules/$slug'
    | '/en/modules/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/boot'
    | '/cordis'
    | '/events'
    | '/faq'
    | '/glossary'
    | '/loop'
    | '/map'
    | '/principles'
    | '/seams'
    | '/story'
    | '/api/locale-suggestion'
    | '/en/boot'
    | '/en/cordis'
    | '/en/events'
    | '/en/faq'
    | '/en/glossary'
    | '/en/loop'
    | '/en/map'
    | '/en/principles'
    | '/en/seams'
    | '/en/story'
    | '/modules/$slug'
    | '/en'
    | '/modules'
    | '/en/modules/$slug'
    | '/en/modules'
  id:
    | '__root__'
    | '/'
    | '/boot'
    | '/cordis'
    | '/en'
    | '/events'
    | '/faq'
    | '/glossary'
    | '/loop'
    | '/map'
    | '/modules'
    | '/principles'
    | '/seams'
    | '/story'
    | '/api/locale-suggestion'
    | '/en/boot'
    | '/en/cordis'
    | '/en/events'
    | '/en/faq'
    | '/en/glossary'
    | '/en/loop'
    | '/en/map'
    | '/en/modules'
    | '/en/principles'
    | '/en/seams'
    | '/en/story'
    | '/modules/$slug'
    | '/en/'
    | '/modules/'
    | '/en/modules/$slug'
    | '/en/modules/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BootRoute: typeof BootRoute
  CordisRoute: typeof CordisRoute
  EnRoute: typeof EnRouteWithChildren
  EventsRoute: typeof EventsRoute
  FaqRoute: typeof FaqRoute
  GlossaryRoute: typeof GlossaryRoute
  LoopRoute: typeof LoopRoute
  MapRoute: typeof MapRoute
  ModulesRoute: typeof ModulesRouteWithChildren
  PrinciplesRoute: typeof PrinciplesRoute
  SeamsRoute: typeof SeamsRoute
  StoryRoute: typeof StoryRoute
  ApiLocaleSuggestionRoute: typeof ApiLocaleSuggestionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boot': {
      id: '/boot'
      path: '/boot'
      fullPath: '/boot'
      preLoaderRoute: typeof BootRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cordis': {
      id: '/cordis'
      path: '/cordis'
      fullPath: '/cordis'
      preLoaderRoute: typeof CordisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en': {
      id: '/en'
      path: '/en'
      fullPath: '/en'
      preLoaderRoute: typeof EnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary': {
      id: '/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof GlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loop': {
      id: '/loop'
      path: '/loop'
      fullPath: '/loop'
      preLoaderRoute: typeof LoopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules': {
      id: '/modules'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof ModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/principles': {
      id: '/principles'
      path: '/principles'
      fullPath: '/principles'
      preLoaderRoute: typeof PrinciplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seams': {
      id: '/seams'
      path: '/seams'
      fullPath: '/seams'
      preLoaderRoute: typeof SeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/locale-suggestion': {
      id: '/api/locale-suggestion'
      path: '/api/locale-suggestion'
      fullPath: '/api/locale-suggestion'
      preLoaderRoute: typeof ApiLocaleSuggestionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/': {
      id: '/en/'
      path: '/'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/boot': {
      id: '/en/boot'
      path: '/boot'
      fullPath: '/en/boot'
      preLoaderRoute: typeof EnBootRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/cordis': {
      id: '/en/cordis'
      path: '/cordis'
      fullPath: '/en/cordis'
      preLoaderRoute: typeof EnCordisRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/events': {
      id: '/en/events'
      path: '/events'
      fullPath: '/en/events'
      preLoaderRoute: typeof EnEventsRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/faq': {
      id: '/en/faq'
      path: '/faq'
      fullPath: '/en/faq'
      preLoaderRoute: typeof EnFaqRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/glossary': {
      id: '/en/glossary'
      path: '/glossary'
      fullPath: '/en/glossary'
      preLoaderRoute: typeof EnGlossaryRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/loop': {
      id: '/en/loop'
      path: '/loop'
      fullPath: '/en/loop'
      preLoaderRoute: typeof EnLoopRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/map': {
      id: '/en/map'
      path: '/map'
      fullPath: '/en/map'
      preLoaderRoute: typeof EnMapRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/modules': {
      id: '/en/modules'
      path: '/modules'
      fullPath: '/en/modules'
      preLoaderRoute: typeof EnModulesRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/principles': {
      id: '/en/principles'
      path: '/principles'
      fullPath: '/en/principles'
      preLoaderRoute: typeof EnPrinciplesRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/seams': {
      id: '/en/seams'
      path: '/seams'
      fullPath: '/en/seams'
      preLoaderRoute: typeof EnSeamsRouteImport
      parentRoute: typeof EnRoute
    }
    '/en/story': {
      id: '/en/story'
      path: '/story'
      fullPath: '/en/story'
      preLoaderRoute: typeof EnStoryRouteImport
      parentRoute: typeof EnRoute
    }
    '/modules/': {
      id: '/modules/'
      path: '/'
      fullPath: '/modules/'
      preLoaderRoute: typeof ModulesIndexRouteImport
      parentRoute: typeof ModulesRoute
    }
    '/modules/$slug': {
      id: '/modules/$slug'
      path: '/$slug'
      fullPath: '/modules/$slug'
      preLoaderRoute: typeof ModulesSlugRouteImport
      parentRoute: typeof ModulesRoute
    }
    '/en/modules/': {
      id: '/en/modules/'
      path: '/'
      fullPath: '/en/modules/'
      preLoaderRoute: typeof EnModulesIndexRouteImport
      parentRoute: typeof EnModulesRoute
    }
    '/en/modules/$slug': {
      id: '/en/modules/$slug'
      path: '/$slug'
      fullPath: '/en/modules/$slug'
      preLoaderRoute: typeof EnModulesSlugRouteImport
      parentRoute: typeof EnModulesRoute
    }
  }
}

interface EnModulesRouteChildren {
  EnModulesSlugRoute: typeof EnModulesSlugRoute
  EnModulesIndexRoute: typeof EnModulesIndexRoute
}

const EnModulesRouteChildren: EnModulesRouteChildren = {
  EnModulesSlugRoute: EnModulesSlugRoute,
  EnModulesIndexRoute: EnModulesIndexRoute,
}

const EnModulesRouteWithChildren = EnModulesRoute._addFileChildren(
  EnModulesRouteChildren,
)

interface EnRouteChildren {
  EnBootRoute: typeof EnBootRoute
  EnCordisRoute: typeof EnCordisRoute
  EnEventsRoute: typeof EnEventsRoute
  EnFaqRoute: typeof EnFaqRoute
  EnGlossaryRoute: typeof EnGlossaryRoute
  EnLoopRoute: typeof EnLoopRoute
  EnMapRoute: typeof EnMapRoute
  EnModulesRoute: typeof EnModulesRouteWithChildren
  EnPrinciplesRoute: typeof EnPrinciplesRoute
  EnSeamsRoute: typeof EnSeamsRoute
  EnStoryRoute: typeof EnStoryRoute
  EnIndexRoute: typeof EnIndexRoute
}

const EnRouteChildren: EnRouteChildren = {
  EnBootRoute: EnBootRoute,
  EnCordisRoute: EnCordisRoute,
  EnEventsRoute: EnEventsRoute,
  EnFaqRoute: EnFaqRoute,
  EnGlossaryRoute: EnGlossaryRoute,
  EnLoopRoute: EnLoopRoute,
  EnMapRoute: EnMapRoute,
  EnModulesRoute: EnModulesRouteWithChildren,
  EnPrinciplesRoute: EnPrinciplesRoute,
  EnSeamsRoute: EnSeamsRoute,
  EnStoryRoute: EnStoryRoute,
  EnIndexRoute: EnIndexRoute,
}

const EnRouteWithChildren = EnRoute._addFileChildren(EnRouteChildren)

interface ModulesRouteChildren {
  ModulesSlugRoute: typeof ModulesSlugRoute
  ModulesIndexRoute: typeof ModulesIndexRoute
}

const ModulesRouteChildren: ModulesRouteChildren = {
  ModulesSlugRoute: ModulesSlugRoute,
  ModulesIndexRoute: ModulesIndexRoute,
}

const ModulesRouteWithChildren =
  ModulesRoute._addFileChildren(ModulesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BootRoute: BootRoute,
  CordisRoute: CordisRoute,
  EnRoute: EnRouteWithChildren,
  EventsRoute: EventsRoute,
  FaqRoute: FaqRoute,
  GlossaryRoute: GlossaryRoute,
  LoopRoute: LoopRoute,
  MapRoute: MapRoute,
  ModulesRoute: ModulesRouteWithChildren,
  PrinciplesRoute: PrinciplesRoute,
  SeamsRoute: SeamsRoute,
  StoryRoute: StoryRoute,
  ApiLocaleSuggestionRoute: ApiLocaleSuggestionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
