/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BootRouteImport } from './routes/boot'
import { Route as CordisRouteImport } from './routes/cordis'
import { Route as EventsRouteImport } from './routes/events'
import { Route as GlossaryRouteImport } from './routes/glossary'
import { Route as LoopRouteImport } from './routes/loop'
import { Route as MapRouteImport } from './routes/map'
import { Route as ModulesRouteImport } from './routes/modules'
import { Route as PrinciplesRouteImport } from './routes/principles'
import { Route as SeamsRouteImport } from './routes/seams'
import { Route as StoryRouteImport } from './routes/story'
import { Route as ModulesSlugRouteImport } from './routes/modules.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BootRoute = BootRouteImport.update({
  id: '/boot',
  path: '/boot',
  getParentRoute: () => rootRouteImport,
} as any)
const CordisRoute = CordisRouteImport.update({
  id: '/cordis',
  path: '/cordis',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryRoute = GlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const LoopRoute = LoopRouteImport.update({
  id: '/loop',
  path: '/loop',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesRoute = ModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => rootRouteImport,
} as any)
const PrinciplesRoute = PrinciplesRouteImport.update({
  id: '/principles',
  path: '/principles',
  getParentRoute: () => rootRouteImport,
} as any)
const SeamsRoute = SeamsRouteImport.update({
  id: '/seams',
  path: '/seams',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesSlugRoute = ModulesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ModulesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/boot': typeof BootRoute
  '/cordis': typeof CordisRoute
  '/events': typeof EventsRoute
  '/glossary': typeof GlossaryRoute
  '/loop': typeof LoopRoute
  '/map': typeof MapRoute
  '/modules': typeof ModulesRouteWithChildren
  '/principles': typeof PrinciplesRoute
  '/seams': typeof SeamsRoute
  '/story': typeof StoryRoute
  '/modules/$slug': typeof ModulesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/boot': typeof BootRoute
  '/cordis': typeof CordisRoute
  '/events': typeof EventsRoute
  '/glossary': typeof GlossaryRoute
  '/loop': typeof LoopRoute
  '/map': typeof MapRoute
  '/modules': typeof ModulesRouteWithChildren
  '/principles': typeof PrinciplesRoute
  '/seams': typeof SeamsRoute
  '/story': typeof StoryRoute
  '/modules/$slug': typeof ModulesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/boot': typeof BootRoute
  '/cordis': typeof CordisRoute
  '/events': typeof EventsRoute
  '/glossary': typeof GlossaryRoute
  '/loop': typeof LoopRoute
  '/map': typeof MapRoute
  '/modules': typeof ModulesRouteWithChildren
  '/principles': typeof PrinciplesRoute
  '/seams': typeof SeamsRoute
  '/story': typeof StoryRoute
  '/modules/$slug': typeof ModulesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/boot'
    | '/cordis'
    | '/events'
    | '/glossary'
    | '/loop'
    | '/map'
    | '/modules'
    | '/principles'
    | '/seams'
    | '/story'
    | '/modules/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/boot'
    | '/cordis'
    | '/events'
    | '/glossary'
    | '/loop'
    | '/map'
    | '/modules'
    | '/principles'
    | '/seams'
    | '/story'
    | '/modules/$slug'
  id:
    | '__root__'
    | '/'
    | '/boot'
    | '/cordis'
    | '/events'
    | '/glossary'
    | '/loop'
    | '/map'
    | '/modules'
    | '/principles'
    | '/seams'
    | '/story'
    | '/modules/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BootRoute: typeof BootRoute
  CordisRoute: typeof CordisRoute
  EventsRoute: typeof EventsRoute
  GlossaryRoute: typeof GlossaryRoute
  LoopRoute: typeof LoopRoute
  MapRoute: typeof MapRoute
  ModulesRoute: typeof ModulesRouteWithChildren
  PrinciplesRoute: typeof PrinciplesRoute
  SeamsRoute: typeof SeamsRoute
  StoryRoute: typeof StoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boot': {
      id: '/boot'
      path: '/boot'
      fullPath: '/boot'
      preLoaderRoute: typeof BootRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cordis': {
      id: '/cordis'
      path: '/cordis'
      fullPath: '/cordis'
      preLoaderRoute: typeof CordisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary': {
      id: '/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof GlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loop': {
      id: '/loop'
      path: '/loop'
      fullPath: '/loop'
      preLoaderRoute: typeof LoopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules': {
      id: '/modules'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof ModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/principles': {
      id: '/principles'
      path: '/principles'
      fullPath: '/principles'
      preLoaderRoute: typeof PrinciplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seams': {
      id: '/seams'
      path: '/seams'
      fullPath: '/seams'
      preLoaderRoute: typeof SeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules/$slug': {
      id: '/modules/$slug'
      path: '/$slug'
      fullPath: '/modules/$slug'
      preLoaderRoute: typeof ModulesSlugRouteImport
      parentRoute: typeof ModulesRoute
    }
  }
}

interface ModulesRouteChildren {
  ModulesSlugRoute: typeof ModulesSlugRoute
}

const ModulesRouteChildren: ModulesRouteChildren = {
  ModulesSlugRoute: ModulesSlugRoute,
}

const ModulesRouteWithChildren =
  ModulesRoute._addFileChildren(ModulesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BootRoute: BootRoute,
  CordisRoute: CordisRoute,
  EventsRoute: EventsRoute,
  GlossaryRoute: GlossaryRoute,
  LoopRoute: LoopRoute,
  MapRoute: MapRoute,
  ModulesRoute: ModulesRouteWithChildren,
  PrinciplesRoute: PrinciplesRoute,
  SeamsRoute: SeamsRoute,
  StoryRoute: StoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
